AUTHORIZATION_ENDPOINT = "/authorization"
PROFILE_ENDPOINT = "/profile"
SUBSCRIPTIONS_ENDPOINT = "/subscriptions"
POSTS_ENDPOINT = "/posts"
COMMENTS_ENDPOINT = "/comments"

API_V1 = "/v1"

AUTHORIZATION_ENABLED_ENDPOINTS = [PROFILE_ENDPOINT, SUBSCRIPTIONS_ENDPOINT]
